### ISSUE TITLE
 Erreur à l'insertion n°2 : Incorrect integer value: '' for column 'bn_sem_use_template' at row 1

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki-extension-ferme#11]
Tentative de création d'un wiki sur une ferme à jour sur un doryphore 2020-10-13-1 (extension ferme à jour : 2020-07-09-1)
Le wiki est bien créé mais pas la fiche bazar. On aboutit à une page blanche portant `Erreur à l'insertion n°2 : Incorrect integer value: '' for column 'bn_sem_use_template' at row 1`.

**Help!** Je suis sur le site reseau.animacoop.net et la ferme doit fonctionner avant la fin de la semaine prochaine !
Est-ce que quelqu'un a une piste évidente et peut me dire ou fouiller ou corriger ou est-ce que je me débrouille ?

Même problème sur une ferme en cercopitheque 2020-06-05-1 (extension ferme à jour et ça fonctionnait avant cette version : 2020-07-09-1).

Pourtant dans le wiki créé, le champ `bn_sem_use_template` de la table `nature` est bien créé de type `tinyint(1)` avec une valeur par défaut de 1. 
Le wiki créé fonctionne, c'est uniquement la fiche qui n'est pas créée dans la ferme.

**Remarque sur les messages d'erreurs** Je propose les règles suivantes (@mrflos, @acheype) à discuter bien sûr  :
- Utiliser le système de localisation et la fonction `_t()`
- Pour faciliter le *debugage*, utiliser un message différent si la mếme erreur intervient à deux endroits différents du code (ici on `die` sur le même libellé lignes 672 et 697 de `ferme.functions.php`.

**Comment by sylvainboyer** [comment]
@mrflos, @acheype  Problème relevé également par Stéphane Pinon sur ferme.yeswiki.net
- page blanche avec message `Erreur à l'insertion n°2 : Incorrect integer value: '' for column yeswikinsuferme.yeswiki_toulouse_atelier__nature.bn_sem_use_template at row 1`
- pas de fiche bazar créée
- wiki créé  : https://ferme.yeswiki.net/toulouse-atelier
Florian, Adrien, je vous *pingue* parce que pour moi le prolème est introduit par la version 2020-07-09-1 de la ferme. Avez-vous des pistes ?

**Comment by mrflos** [comment]
j'ai pas le temps de regarder, mais ya clairement un soucis sur le contenu du fichier sql (il donne un string vide pour bn_sem_use_template alors qu'un entier est attendu).  
Je push un truc, mais j'aurai pas le temps de tester..

**Comment by sylvainboyer** [comment]
:clap: Si tu *push*, je me débrouille pour que ce soit massivement *tested*
Merci beaucoup @mrflos

**Comment by mrflos** [comment]
J'ai pushé et créé le paquet, c'est en place sur https://ferme.yeswiki.net  
J'ai remarqué un rapport de création de table, dans une popup de notification, je suis pas sûr que ce soit une bonne idée (seul les devs devraient voir cela, et comme c'est dans une popup de toute facon on ne peut pas le lire.. )

**Comment by sylvainboyer** [comment]
Merci @mrflos ,
Installation nickel depuis l'IHM de GererMisesAJour sur les trois fermes animacoop.
Mes tests sont concluants pour le moment. J'ai demandé à mes GU (*gentils utilisateurs*) de tester sur https://bacasable.animacoop.net (*cercopithèque*) et sur https://ferme.yeswiki.net.

Et je confirme que la *pop-up* est très sale.
J'attends le résultat des tests pour clôre.

**Comment by sylvainboyer** [comment]
*pop-up* ligne 702  de `ferme.functions.php`
Je vire ?

**Comment by acheype** [comment]
Hello,
Le pop-up c'est moi. Quand j'ai commencé à reprendre le code de la ferme, les scripts n'étaient plus à jour et j'ai amélioré le code pour avoir un retour des insertions SQL.
Je l'ai mis en popup car j'ai l'impression que c'est le seul mécanisme qui permet d'afficher un message à la page suivante. J'ai eu le même besoin pour le module login-sso donc les popup s'affichent 10s sur mes serveurs pour ce type de retour long (en attendant de trouver mieux).

   - C'est sûr que pour des utilisateurs classiques, ça n'a pas trop d'intéret d'afficher le log des insertions mais est-ce qu'on pourrait pas l'afficher uniquement pour l'admin ? (perso je modifie les scripts générés par la ferme à la mano donc ça peut être utile pour ce type d'utilisation).

-  Pour l'affichage, si vous avez une autre solution pour afficher un msg sur la page suivante sans gérer spécifiquement l'affichage du msg sur cette page, je suis preneur.

**Comment by sylvainboyer** [comment]
Salut Adrien,
Afficher pour l'admin en attendant de trouver mieux.
L'ideal serait d'afficher en mode debug uniquement.
Sinon, moi quand j'ai besoin, j'utilise $_POST mais ça nécessite de le tester systématiquement pour être certain de ne pas avoir à afficher de message. Mais, c'est robuste et tu peux gérer ton contexte.
