### ISSUE TITLE
Cerco - fichier sql source importé dans files

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki-extension-ferme#12]
Ferme (v. 2020-10-16-1) sur un wiki en cercopitheque 2020-06-05-1.
Lors de l'import d'un fichier sql source, on obtient une page blanche avec le  message *Le fichier sql "tools/ferme/sql/source.animacoop.net.sql" n'a pas été trouvé.*
Le fichier en question se trouve dans `/files` au lieu de `/tools/ferme/sql`

**Comment by acheype** [comment]
Slt Sylvain,
A te lire, j'ai l'impression que c'est juste que tu n'as pas déplacé le fichier dans /tools/ferme/sql/.
En effet {{generatemodel}} créé le modèle dans /files et il faut aller le déplacer à la main et renseigner le wakka.config avec le bon nom de fichier.

**Comment by sylvainboyer** [comment]
Bonjour Adrien,
C'est bien ce que dit le titre de cette *issue*. 
Le fichier est importé dans `/files`.
Et il doit être dans `/tools/ferme/sql` pour pouvoir être utilisé.
L'*issue* porte donc sur le fait de devoir déplacer le fichier à la main. :stuck_out_tongue_winking_eye:

**Comment by acheype** [comment]
ah ok, je pensais que tu relevais un bug... mais pas une proposition d'amélioration.

à voir si la dernière version que flo a déployé ne change pas ce comportement. je ne l'ai pas encore testée.

**Comment by mrflos** [comment]
oui, ca a encore changé, c'est maintenant une arborescence dans custom/wiki-models , avec un dossier par modele, et la possibilité d'avoir des dossiers customs par modeles et un dossier files pré-approvisionné par modele.
La liaison entre l'interface des imports/sync de modeles n'est cependant pas encore terminée.

**Comment by sylvainboyer** [comment]
Ça a l'air super. Merci @mrflos.
J'avoue avoir mis mes fermes à jour mais pas tout retesté.
Tu dis que ça récupère aussi le dossier `\files` ? C'est carrément génial !
J'attends le bout qui manque avec gourmandise.

**Comment by mrflos** [comment]
Ah, part contre je viens de voir que cette issue était pour cercopitheque, et les modifs que j'ai fait sont pour doryphore seulement..
Je propose de laisser cette issue ouverte et corriger l'emplacement du sql pour que dans la version cerco, tout point bien vers le dossier files (seule option viable car le dossier tools est écrasé à chaque maj).
Merci pour tes retours enthousiastes @sylvainboyer , pour l'import du dossier files et du dossier custom par modele, je te tiendrai au courant

**Comment by sylvainboyer** [comment]
Si cela focntionne en `doryphore`, cela me va.
En ce qui concerne `cercopitheque`, je n'y suis pas attaché. Et je ne conservais des fermes en `cercopitheque` que dans la mesure où nous avions convenu que c'était la seule version stable et qu'il fallait que je fasse des tests sur les deux versions. Si on dit que pour qu'une ferme fonctionne il faut passer en `doryphore`, j'en suis content (et je m'y précipite).

**Comment by sylvainboyer** [comment]
Nickel, 
Merci
