### ISSUE TITLE
Problème de création d'un wiki avec la ferme Doriphohre

### ISSUE THREAD

**Issue by ericfavr3** [YesWiki/yeswiki-extension-ferme#17]
Problème lors de la création d'un wiki.

Mon dossier /wiki est en 777

Version du Wiki : doryphore 2021-05-25-2
Ferme&nbsp;(documentation)Gérer une ferme à wikis a partir d'un formulaire bazar | 2021-06-06-5 | 2021-06-06-5 | &nbsp; | 

![Capture d’écran du 2021-06-17 17-28-44](https://user-images.githubusercontent.com/54939115/122428714-7466c880-cf92-11eb-8759-118d7a7669a2.png)

**Comment by mrflos** [comment]
hello, j'avais pas vu ce ticket, c'est encore d'actualité?

**Comment by mrflos** [comment]
ping @ericfavr3
