### ISSUE TITLE
Manque un fichier 

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki-extension-ferme#2]
Hello, lorsque l'on veut afficher dans une page le formulaire de création, on reçoit le message d'erreur "Le fichier "tools/ferme/screenshots/yeswiki.jpg" n'a pas été trouvé.".
Il faut alors le créer soi-même à la racine. Je ne sais pas si c'est sur l'extension ou sur yeswiki qu'il faut agir donc je met ça là :-)

**Comment by sylvainboyer** [comment]
Problème absent des dernières versions.
