### ISSUE TITLE
Problème dans l'URL des wikis créés

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki-extension-ferme#3]
Hello, 
Dans les wikis créés via la ferme, les liens vers des pages (menu, pages créées,...) pointent vers l'URL "www.maferme.truc/?" au lieu de pointer vers "www.maferme.truc/monsouswiki/?".
Un exemple là : https://formations.osons.cc/?PageListe

**Comment by sylvainboyer** [comment]
La doc a été corrigée sur ce point.
Pour moi cela fonctionne.
Est-ce que tu valides @RomainLalande ?
