### ISSUE TITLE
Gestion des utilisateurs ferme

### ISSUE THREAD

**Issue by RomainLalande** [YesWiki/yeswiki-extension-ferme#4]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
New feature / Nouvelle fonctionnalité

**Description**
Sur la ferme, permettre aux utilisateurs de changement de l'adresse mail

**Comment by mrflos** [comment]
tu parles de celle demandée avec la fiche bazar ou le WikiAdmin du wiki crée?

**Comment by RomainLalande** [comment]
Oulala de mémoire vu la date ce devait être une capitalisation des post-it du sprint de Vedène, dont je n'étais surement même pas l'auteur x)
Donc je ne sais pas répondre :s

**Comment by mrflos** [comment]
sur la fiche, c'est possible maintenant, par contre le WikiAdmin du wiki, c'est plus compliqué et pas encore fait

**Comment by mrflos** [comment]
je ferme l'issue en attendant qu'elle soit plus détaillée.
