### ISSUE TITLE
Magnifique page blanche avec {{adminwikis}}

### ISSUE THREAD

**Issue by sylvainboyer** [YesWiki/yeswiki-extension-ferme#7]
Avec la dernière version de la ferme, on obtient une page blanche avec l'action {{adminwikis}}.

**Comment by mrflos** [comment]
mets &debug dans l'url pour voir l'erreur

**Comment by sylvainboyer** [comment]
Je l'avais fait et j'ai la même chose, c'est blanc

**Comment by sylvainboyer** [comment]
Problème toujours existant après chargement de la dernière version de la ferme sur bacasable.animacoop.net (cercopitheque 2020-02-29-1).

**Comment by mrflos** [comment]
tu l'as récupères ou la dernière version de la ferme? depuis git?

**Comment by sylvainboyer** [comment]
Oui

**Comment by mrflos** [comment]
ca va mieux avec la nouvelle version?

**Comment by sylvainboyer** [comment]
Toujours pareil sur cercopitheque.
- https://osons.cc/BacASable/?GererWikis
- https://bacasable.animacoop.net/?GererWikis

Comportement correct sur dev
- https://formations.osons.cc/?AdminWikis

**Comment by mrflos** [comment]
je ne me souviens plus du mot de passe pour le bac a sable osons @sylvainboyer , si tu peux me le renvoyer par MP sur mattermost, par exemple, merci!

**Comment by sylvainboyer** [comment]
sur doryphore 2020-10-13-1 on a toujours un truc qui va pas.
Tu cliques sur le bouton pour avoir ton super user sur un wiki et la page revient avec le titre seul ("Administration de tous les wikis").
Et si tu retires, dans la barre d'adresse les paramètres (`&superadmin=verbatimludique`) tu récupères un comportement correct. Même chose quand tu retires le superadmin d'un wiki (`&nosuperadmin=verbatimludique`).

**Comment by sylvainboyer** [comment]
Sur doryphore 2020-10-23-1 ou 2020-10-13-1, avec une ferme (https://reseau.animacoop.net/?PopAdmin) en 2020-10-16-1, on a toujours le même problème.
`{{adminwikis}}` renvoie une page blanche en 2020-10-13-1
et une page blanche avec le titre "Administration de tous les wikis" en 2020-10-23-1

**Comment by mrflos** [comment]
si tu es sur la dernière version doryphore, il faudrait prendre https://github.com/YesWiki/yeswiki-extension-ferme/tree/adapt-to-bazar-refactoring pour avoir les bonnes fonctions bazar.
Je n'ai pas eu le temps de faire les différentes branches pour les version cercopitheque et doryphore concernant les extensions..

**Comment by sylvainboyer** [comment]
Je viens de mettre cette branche en place. Comportement inchangé :disappointed:

**Comment by mrflos** [comment]
ca marche sur la ferme à wikis ferme.yeswiki.net pourtant..  

Essayes de passer mon dernier commit de la version dev: mettre la méthode decode() en public dans le fichier tools/bazar/libs/bazar.fonct.retrocompatibility.php 

`    public function decode($body)`

**Comment by sylvainboyer** [comment]
J'ai planté mon Wiki avec ça (plus d'affichage de pages). Je suis revenu à une version doryphore standard.

**Comment by sylvainboyer** [comment]
@mrflos Après notre conversation de ce matin, j'ai modifié `/tools/bazar/libs/BazarFiche.class.php` (et non pas dans `tools/bazar/libs/bazar.fonct.retrocompatibility.php`) en remplaçant (l. 535) `protected function decode($body)` par `public function decode($body)`.
- Avec `protected`, seul le titre "Administration de tous les wikis" s'affiche.
   En mode debug, on a : `Fatal error: Uncaught Error: Call to protected method YesWiki\BazarFiche::decode() from context '' in /srv/data/web/vhosts/reseau.animacoop.net/htdocs/tools/bazar/libs/bazar.fonct.retrocompatibility.php:66 Stack trace: #0 /srv/data/web/vhosts/reseau.animacoop.net/htdocs/tools/ferme.old/actions/adminwikis.php(188): searchResultstoArray(Array, Array, '') #1 /srv/data/web/vhosts/reseau.animacoop.net/htdocs/includes/YesWiki.php(1430): include('/srv/data/web/v...') #2 /srv/data/web/vhosts/reseau.animacoop.net/htdocs/includes/YesWiki.php(1242): YesWiki\Wiki->IncludeBuffered('adminwikis.php', '<div class="ale...', Array, 'tools/toc/actio...') #3 /srv/data/web/vhosts/reseau.animacoop.net/htdocs/formatters/wakka.php(339): YesWiki\Wiki->Action('adminwikis') #4 [internal function]: YesWiki\WikiniFormatter->callback(Array) #5 /srv/data/web/vhosts/reseau.animacoop.net/htdocs/formatters/wakka.php(66): preg_replace_callback('/\\%\\%.*?\\%\\%|""...', Array, '{{adminwikis}}\n') #6 /srv/data/web/vhosts/reseau.animacoop.net/htdocs/formatter in /srv/data/web/vhosts/reseau.animacoop.net/htdocs/tools/bazar/libs/bazar.fonct.retrocompatibility.php on line 66`
- Avec `public`, la page est entièrement blanche (y compris en mode debug).

En résumé, 
- en **cercopitheque** (dernière version : 2020-06-05-1 et ferme 2020-10-16-1) => page totalement blanche (y compris en debug) :
  - https://bacasable.animacoop.net/?GererWikis
  - https://sessions.animacoop.net/?GererWikis
- en **doryphore** (dernière version : 2020-10-23-1 et ferme 2020-10-16-1) => affichage du titre "Administration de tous les wikis"  seul :
  - https://reseau.animacoop.net/?PopAdmin
  - https://osons.cc/BacASable/?GererWikis

J'attends donc des instructions ou la prochaine *release*.

**Comment by sylvainboyer** [comment]
En doryphore `2021-05-04-5` avec une extension ferme en `2021-05-03-1` on a une page blanche avec l'action `{{adminwikis}}`.
=> visible là : https://bacasable.animacoop.net/?GererWikis

Même comportement en `cercopitheque 2021-04-21-1` avec une extension ferme en `2020-11-17-3 `.
=> visible là : https://sessions.animacoop.net/?GererWikis

Me contacter pour avoir un compte en admin sur l'une ou l'autre de ces fermes.

**Comment by sylvainboyer** [comment]
Avec la dernière version, il n'y a plus de page blanche.
